apiVersion: v1
kind: ConfigMap
metadata:
  name: supernova-configmap
  namespace: refael
data:
  master: refael
SS_SPIKE_CLIENT_ID: bwwIB0gSS0xay_odirl0OCAJ3gUlXkKMKijbDY_e
SS_SPIKE_CLIENT_SECRET: 9FlWUMIVykj9r9iZoRq9o~1v4WP~1GJ49qlaAX7K3xXKIK6KePmRY~9B1X6EQPC00Hg~FBdTsU_EPNqmeZmZ5DbJ3feYwLN1hQg9
SS_USE_REDIS: 'true'
SS_REDIS_HOST: redis
SS_REDIS_PORT: '6379'
SS_REDIS_PASSWORD: mozart
SS_SPIKE_TOKEN_URL: https://ospike.northeurope.cloudapp.azure.com/oauth2/token
SS_SPIKE_PUBKEY_PATH: https://ospike.northeurope.cloudapp.azure.com/.well-known/publickey.pem
SS_SPIKE_PUBLIC_KEY_FULL_PATH: /spikeUtils/publickey.pem
SS_SHMUEL_AUDIENCE: shmuel
SS_KARTOFFEL_AUDIENCE: kartoffel
SS_GRANT_TYPE: client_credentials
SS_HOST: 0.0.0.0
SS_PORT: '8080'
SS_LOG_PATH: /logs
RS_MONGO_URL: mongodb://mongo:27017/supernova
RS_HOST: 0.0.0.0
RS_PORT: '8081'
RS_NS_URL: notification-service:8080
RS_TS_URL: tea-service:8080
RS_MS_URL: mail-service:8080
RS_ROOT_ID: 619e3193f235dc001846bb4f
RS_LOG_PATH: /logs
KS_HOST: 0.0.0.0
KS_PORT: '8082'
KS_KARTOFFEL_URL: http://52.188.158.174:7709
KS_SS_URL: spike-service:8080
KS_USE_FAKER: 'true'
KS_KARTOFFEL_AUDIENCE: kartoffel
KS_SPIKE_TOKEN_REFRESH_HOURS: '24'
KS_COMMANDER_RANKS: aaaa,bbbb,cccc,ssss
KS_HIGH_COMMANDER_RANKS: aaaa,bbbb,cccc,ssss
KS_ROOT_ID: 6184af202da776001134110b
KS_DEFAULT_OG_SOURCE: sf_name
KS_DEFAULT_ROLE_SOURCE: sf_name
KS_DEFAULT_DI_SOURCE: sf_name
KS_DI_SOURCES: sf_name,sf_name
KS_SEARCH_WITH_RANKS: 'true'
KS_TREE_DEPTH: '3'
KS_LOG_PATH: /logs
EXS_RS_URL: request-service:8080
EXS_PS_URL: producer-service:8080
EXS_APS_URL: approver-service:8080
EXS_MINUTE: '5'
EXS_CRON_JOB: 'false'
EXS_ROOT_ID: 619e3193f235dc001846bb4f
EXS_LOG_PATH: /logs
WLS_APS_URL: approver-service:8080
WLS_HOUR: '0'
WLS_MINUTE: '0'
WLS_CRON_JOB: 'false'
WLS_LOG_PATH: /logs
AIS_KS_URL: kartoffel-service:8080
AIS_APS_URL: approver-service:8080
AIS_EXCEL_FILE_PATH: /excelFiles/AISExcelFile.xlsx
AIS_LOG_PATH: /logs
PS_HOST: 0.0.0.0
PS_PORT: '8083'
PS_QUEUE_API_URL: http://20.199.120.227:3000
PS_RS_URL: request-service:8080
PS_DEV_MODE: 'true'
PS_SHMUEL_AUDIENCE: shmuel
PS_SS_URL: spike-service:8080
PS_SPIKE_TOKEN_REFRESH_HOURS: '24'
PS_OLD_DOMAIN: oldDomain
PS_NEW_DOMAIN: newDomain
PS_RESTRICT_AD_ACCESS: 'false'
PS_AD_ALLOWED_SUBMITTERS: 1111,2222,3333,4444
PS_AD_UPN_SUFFIX: gmail.com
PS_LOG_PATH: /logs
AS_PORT: '8080'
AS_ENDPOINT: http://localhost:9000/auth
AS_ALLOWED_ORIGINS: http://localhost/
AS_TOKEN: sp-token
AS_SECRET_KEY: superNova
AS_TOKEN_DAYS_EXPIRES: '30'
AS_PROFILE_EXTRACTOR_ID: id
AS_PROFILE_EXTRACTOR_MAIL: mail
AS_PROFILE_EXTRACTOR_FIRST_NAME: givenName
AS_PROFILE_EXTRACTOR_LAST_NAME: surName
AS_PROFILE_EXTRACTOR_JOB: job
AS_STRATEGY: shraga
AS_SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
AS_SHRAGA_USE_ENRICH_ID: 'true'
AS_SHRAGA_PROVIDERS: Genesis
AS_CLIENT_ENDPOINT: http://localhost:2000
AS_KS_URL: kartoffel-service:8080
AS_APS_URL: approver-service:8080
AS_KARTOFFEL_ENRICH: 'false'
AS_APPROVER_ENRICH: 'true'
AS_USE_SHRAGA_LOCAL_MAP: 'true'
AS_SHRAGA_LOCAL_MAP_IDS: 619e3a6fe4de0300121d78c7,619e406ee4de0300121dc4c8,619e42b6e4de0300121dc4e3,619e5132e4de0300121dc528,619f8aa0e4de0300121dd3f4
AS_SHRAGA_LOCAL_MAP_DIS: t23458789@jello.com,t25458789@jello.com,t25458711@jello.com,gggUser@rabiran.com,e595300134@turtle.com
AS_LOG_PATH: /logs
GATEWAY_HOST: 0.0.0.0
GATEWAY_PORT: '8080'
GATEWAY_RS_URL: request-service:8080
GATEWAY_KS_URL: kartoffel-service:8080
GATEWAY_PS_URL: producer-service:8080
GATEWAY_NS_URL: notification-service:8080
GATEWAY_APS_URL: approver-service:8080
GATEWAY_BS_URL: bulk-service:8080
GATEWAY_TS_URL: tea-service:8080
GATEWAY_AS_URL: http://localhost:9000
GATEWAY_TOKEN: sp-token
GATEWAY_SECRET_KEY: superNova
GATEWAY_APM_URL: http://apm-server:8200
GATEWAY_SPIKE_AUDIENCE_ID: bwwIB0gSS0xay_odirl0OCAJ3gUlXkKMKijbDY_e
GATEWAY_SPIKE_PUBLIC_KEY_FULL_PATH: /spikeUtils/publickey.pem
GATEWAY_BS_FOLDER_PATH: /bulkFiles
GATEWAY_WRITE_SCOPE_NAME: write
GATEWAY_LOG_PATH: /logs
GATEWAY_USE_APM: 'false'
GATEWAY_AUTHENTICATION_REQUIRED: 'true'
GATEWAY_SUPPORT_LINK: https://www.lego.com/en-us/service
GATEWAY_ROOT_ID: 619e3193f235dc001846bb4f
NS_HOST: 0.0.0.0
NS_PORT: '8084'
NS_MONGO_URL: mongodb://mongo:27017/supernova
NS_LOG_PATH: /logs
APS_HOST: 0.0.0.0
APS_PORT: '8085'
APS_MONGO_URL: mongodb://mongo:27017/supernova
APS_KS_URL: kartoffel-service:8080
APS_RS_URL: request-service:8080
APS_COMMANDER_RANKS: aaaa,bbbb,cccc,ssss
APS_HIGH_COMMANDER_RANKS: bbbb,cccc,ssss
APS_OG_VALIDATION_DEPTH: '4'
APS_ALWAYS_VALID_COMMANDERS: 1111,2222,3333,4444
APS_LOG_PATH: /logs
TS_HOST: 0.0.0.0
TS_PORT: '8086'
TS_MONGO_URL: mongodb://localhost:27017/supernova
TS_SOLDIER: soldier
TS_RESERVED: reserved
TS_CIVILIAN: Civilian
TS_GOAL_USER: goalUser
TS_KS_URL: kartoffel-service:8082
TS_OLD_SUFFIX: gmail.com
TS_NEW_SUFFIX: gmail.com
TS_NEED_INIT: 'true'
TS_INIT_EMPTY_ARRAYS: 'true'
TS_EXCEL_INIT_FOLDER: /teaUtils
TS_EXCEL_INIT_FILE: initPrefixes.xlsx
TS_BROL: brol
TS_LOG_PATH: /logs
BS_HOST: 0.0.0.0
BS_PORT: '8087'
BS_RS_URL: request-service:8080
BS_FOLDER_PATH: /bulkFiles
BS_KARTOFFEL_DOMAIN_USER: domainUser
BS_DEFAULT_ROLE_SUFFIX: sf_name
BS_DEFAULT_ROLE_SOURCE: sf_name
BS_CRH_EXAMPLE_FILE: changeRoleHierarchyBulk.xlsx
BS_CR_EXAMPLE_FILE: createRoleBulk.xlsx
BS_SOLDIER: soldier
BS_RESERVED: reserved
BS_CIVILIAN: civilian
BS_GOAL_USER: goalUser
BS_LOG_PATH: /logs
MS_HOST: 0.0.0.0
MS_PORT: '8088'
MS_LOG_PATH: /logs
MS_KS_URL: kartoffel-service:8080
MS_MAIL_ADDRESS: mayatest4321@outlook.com
MS_MAIL_USER: mayatest4321@outlook.com
MS_MAIL_PASSWORD: testpass4321
MS_MAIL_SERVER_HOST: smtp.office365.com
MS_MAIL_SERVER_PORT: '587'
MS_MAIL_SERVER_SECURE: 'false'
MS_IS_TEST: 'true'
MS_EMAILS_FOR_TEST: enterEmailForTest
POS_RS_URL: request-service:8080
POS_ENTITY_IDS: 111111111111111111111111,222222222222222222222222,333333333333333333333333,444444444444444444444444
POS_GENERATE_COUNT: '50'
POS_LOG_PATH: /logs
KC_RS_URL: request-service:8080
KC_TS_URL: tea-service:8080
KC_KS_URL: kartoffel-service:8080
KC_DEFAULT_ROLE_SOURCE: sf_name
KC_DEFAULT_DI_SOURCE: sf_name
KC_DI_SOURCES: sf_name,sf_name
KC_KAFKA_HOST: 127.0.0.1
KC_KAFKA_PORT: '9092'
KC_KARTOFFEL_GOAL_USER: GoalUser
KC_KARTOFFEL_DOMAIN_USER: domainUser
KC_KAFKA_CONSUMER_TOPIC: requests
KC_CIVILIAN: Civilian
KC_SEND_UPN_TO_KARTOFFEL: 'true'
KC_LOG_PATH: /logs
UI_REACT_APP_BASE_URL: http://localhost:2000
UI_REACT_PAGE_SIZE: '10'
UI_REACT_ITEMS_IN_PAGE: '6'
UI_REACT_FIRST_PAGE: '0'
UI_USER_CITIZEN_ENTITY_TYPE: Civilian
UI_USER_CLEARANCE: 1,2,3,4,5,6
UI_USER_SOURCE_DI: sf_name
UI_USER_NO_PICTURE_STRING: pictureUrl
UI_HIGH_COMMANDER_RANKS: rookie,champion
UI_DI_TYPE: domainUser
UI_ROLE_ENTITY_TYPE: goalUser
GLOBAL_STORE_LOGS: 'true'
GLOBAL_GRPC_POOL_SIZE: '3'
