name: tea-service
replicaCount: 1
images:
  repository: docker.io/refael058325/ci
  tag: tea-service.v0.0.1
service:
  ports:
  - name: http
    port: '3000'
configmap:
  configmaps: tea-service-configmap
ingress:
  enabled: true
  hosts:
  - host: test
    paths:
    - path: peth
      service: test
      port: 80
